Node homework #02
brzozanet/goit-node-hw-02-06 pull request #1
Opened 2024-03-20 12:23 UTC by brzozanet

I left some comments in the code. This makes it easier for me to learn and come back to the code in the future.

2024-03-21 09:56 UTC, KamilMr requested changes
Hej, zobacz jeszcze o PUT https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

Bo trzeba by ją trochę poprawić. Jak cos nie jasne to pisz na slaku,
Pozdrawiam

2024-03-21 09:56 UTC, KamilMr commented on app.js
> +app.use((request, response) => {
```suggestion
app.use((req, res) => {
```
Tak się przyjeło że się pisze.

2024-03-21 09:56 UTC, KamilMr commented on routes/api/contacts.js
> +      next();
Tu zamiast next to zwróć informacje że nie ma kontaktu. 
Czyli res.status().send('Not found') // to dopasuj do tego jak piszesz.

2024-03-21 09:56 UTC, KamilMr commented on routes/api/contacts.js
> +// NOTE: basic validation
Moze lepiej te komentarze trzymać na dole pliku?

2024-03-21 09:56 UTC, KamilMr commented on routes/api/contacts.js
> +      next();
Tu też zamiast next to użyj contact not found, lub możesz też użyć next ale z błędem lub informacją. Np. możesz next(new Error('Contact not found'))

2024-03-21 09:56 UTC, KamilMr commented on routes/api/contacts.js
> +const userPatternPUT = Joi.object({
Podobnie jak Post wymaga, by w ciele żądania znajdował się komplet danych i jeśli taki obiekt już istnieje, to aktualizowane są wszystkie dane. Jeśli nie to albo można stworzyć nowy albo zwrócić informacje że taki obiekt nie istnieje. To co Ty zaimplementowałeś przypomina patch.

2024-03-22 18:55 UTC, brzozanet commented on app.js
> +app.use((request, response) => {
Oki, tak jak rozmawialiśmy na slacku, w kolejnych projektach będę się trzymał skróconej wersji, nie ma co iść pod prąd, zrobiłem to tylko dla czytelności dla samego siebie, pisanego przez siebie kodu :-)

2024-03-22 19:00 UTC, brzozanet commented on routes/api/contacts.js
> +      next();
Ale chyba dokładnie właśnie tak jest (o ile dobrze rozumiem Twoją uwagę) :-) Gdy Zrobisz GET na nieistniejący id, przychodzi JSON'owy response z info "Not found", zaś jest to ogarniane właśnie przez next(), plik app.js: 

https://github.com/brzozanet/goit-node-hw-02-06/blob/2e77aa778c17086dd0c12688f5876d4a3f790168/app.js#L17

![Zrzut ekranu 2024-03-22 195737](https://github.com/brzozanet/goit-node-hw-02-06/assets/117111825/5283fa22-5b0d-4d73-8b3e-d8d6148fb56c)

2024-03-22 19:00 UTC, brzozanet commented on routes/api/contacts.js
> +// NOTE: basic validation
Done :)

2024-03-22 20:31 UTC, brzozanet commented on routes/api/contacts.js
> +      next();
Analogicznie jak dwie uwagi wyżej, komunikat "not found" jest realizowany właśnie dzięki next() -> app.js

2024-03-22 20:48 UTC, brzozanet commented on routes/api/contacts.js
> +const userPatternPUT = Joi.object({
W końcu to zrozumiałem, dzięki :-) Aczkolwiek w tej sytuacji sensowniejsze wydaje się użyć PATCH, wszak możemy chciez zaktualizować jeden, kilka lub wszystkie właściwości zasobu

2024-03-25 20:58 UTC, merged