Node homework #04
brzozanet/goit-node-hw-02-06 pull request #3
Opened 2024-03-31 20:37 UTC by brzozanet

2024-04-02 08:07 UTC, KamilMr requested changes
Hej, komentarze w PR

2024-04-02 08:07 UTC, KamilMr commented on service/index.js
> +  return Contact.create({ owner: userId }, contact);
```suggestion
  return Contact.create({...contact,  owner: userId });
```
Zobacz to sobie, do owner trzeba przypisać userId.

2024-04-02 08:07 UTC, KamilMr commented on service/index.js
> +  return Contact.create({ owner: userId }, contact);
https://mongoosejs.com/docs/api/model.html#Model.create()

2024-04-02 08:07 UTC, KamilMr commented on routes/api/users.js
> +    const user = await Users.findOne({ email: body.email });
tę linię wykonaj dopiero jak zrobisz validację czyli po linii 76

2024-04-02 08:07 UTC, KamilMr commented on routes/api/users.js
> +      return response.status(401).json({ message: `Not authorized` });
authenticateToken już to sprawdzi, nie trzeba dwa razy tego robic.

2024-04-03 11:49 UTC, brzozanet commented on routes/api/users.js
> +    const user = await Users.findOne({ email: body.email });
Done :-)

2024-04-03 19:35 UTC, brzozanet commented on service/index.js
> +  return Contact.create({ owner: userId }, contact);
Done :-)

2024-04-03 19:42 UTC, brzozanet commented
Poza specyfikacją zadania dodałem jeszcze jeden middleware, który na endpoincie localhost:3000/api/users/current sprawdza czy user nie jest zalogowany (czy user.token === null) i jeśli true to zwraca 401 Unathtorized attempt, zaś jeśłi false (czy w bazie jest token usera), to puszcza dalej. W zadaniu nie było na to zwrócone uwagi (albo ja coś wcześniej niedopatrzyłem), ale gdyby tego nie zrobić, to sprawdza usera z request.body a nie z bazy danych => czyli nawet po wylogowaniu a później GET na endpoint current zwracało usera z body.

https://github.com/brzozanet/goit-node-hw-02-06/blob/hw-04-auth/middlewares/userLoggedIn.js

2024-04-04 13:33 UTC, KamilMr approved these changes
Zadanie zatwierdzam ale tego userLoggedIn nie potrzebujesz.

2024-04-04 13:33 UTC, KamilMr commented on middlewares/userLoggedIn.js
Ten middleware nie jest potrzebny, middlewares/authenticate.js zajmuje się sprawdzeniem tokenu.

2024-04-04 13:33 UTC, KamilMr commented on routes/api/users.js
> +  [authenticateToken, userLoggedIn],
```suggestion
  authenticateToken,
```

2024-04-04 13:33 UTC, KamilMr commented on routes/api/users.js
> +  [authenticateToken, userLoggedIn],
To ma wystarczyć. Użytkownik nie zalogowany nie moze iść dalej. Jeśli zalogowany wtedy będzie miał req.user. 
Ma sens?

2024-04-04 18:40 UTC, merged